title: Krynos1's Website
author: Krynos1
email: Krynos1@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my site! Here I will mostly talk about my projects. I may also use this as a portfolio.

# social links
twitter_username: krynos1_1
github_username:  Krynos1

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
